spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: CLIENT_ID
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  jwt:
    secretKey: lleekklleekklleekklleekk0000000lleekklleekksad213dsa213dsacae2eq